### ISSUE TITLE
Win run error.

### ISSUE THREAD

**Issue by foreverluck** [nccgroup/ABPTTS#4]
Python 2.7

[2020-04-21 02:45:55.979000] WARNING: The current configuration ignores TLS/SSL certificate validation errors for connection to the server component. This increases the risk of the communication channel being intercepted or tampered with.
Traceback (most recent call last):
  File "abpttsclient.py", line 671, in <module>
    dataBlockNameValueSeparator = base64.b64decode(conf.dataBlockNameValueSeparatorB64)
  File "C:\Python\lib\base64.py", line 79, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding

**Comment by blincoln682F048A** [comment]
Hi. What do you have for the dataBlockNameValueSeparatorB64 value in your config file? Usually that error would mean you specified something by hand, and didn't base64-encode it.

**Comment by hababy** [comment]
You should add -c ,python2 abpttsclient.py -c config.txt, base64 string's length is an integer multiple of 4.
